Uitwerkingen huiswerk les 2 javascript
Pincodeert/frontend-javascript-huiswerk-loops-arrays-objects pull request #1
Opened 2023-03-27 19:36 UTC by Pincodeert

Hoi, leuk dat je feedback wil geven op mijn code.

2023-03-30 13:04 UTC, JordyHB requested changes
Hoi, 

Netjes gedaan! Hoop dat ik niet te hard overkom door de text. 

Ik zag dat je dieper in het huiswerk al steeds meer spaties ging gebruiken. Het enige wat ECHT belangerijk is, is dat je altijd naar loopt door de .length van een array en voor een vast nummer loopt. Je huidige code houdt op met werken als er 1 item eraf of erbij komt in sommige van je loops.

Fijne dag verder! :)

2023-03-30 13:04 UTC, JordyHB commented on loops.js
> +const asterix = "*";
De variable is hier in principe niet nodig, is een extra stap als je de code wil lezen.

2023-03-30 13:04 UTC, JordyHB commented on loops.js
> +for(let i = 0; i<5; i++){
Vergeet geen spatie tussen na for en tussen het sluitende haakje en de openende acolade.

2023-03-30 13:04 UTC, JordyHB commented on loops.js
> +for(let i = 0; i < 5; i++){
Hier missen wederom wat spaties, Ik zal vanaf hier geen commentaar meer leveren op missende spatie, tenzij het op een nieuwe manier vergeten wordt.

2023-03-30 13:04 UTC, JordyHB commented on loops.js
> +for (let i = 1; i < 101; i++) {
Hier zou je ook i <= 100. zal persoonlijke voorkeur zijn.

2023-03-30 13:04 UTC, JordyHB commented on loops-arrays-objects.js
> +for (let i = 0; i < 4; i++) {
Hoewel dit nu wel werkt breekt dit stukje code als we een extra item aan het array toevoegen. 

Om dit te voorkomen loopen we arrays altijd met i < array.length.

zo loopt hij automatisch meer als de array langer wordt.

2023-03-30 13:04 UTC, JordyHB commented on loops-arrays-objects.js
> +for (let i = 0; i < 4; i++) {
zelfde verhaal als mijn vorige comment.

2023-03-30 13:04 UTC, JordyHB commented on loops-arrays-objects.js
> +    const result = scores[i].score;
Deze variable is ook een extra stap die niet strict nodig is.

2023-03-30 13:04 UTC, JordyHB commented on loops-and-arrays.js
> +    squares[i] = "Het volume van " + squares[i] + " is " + squares[i]*squares[i]*squares[i];
Je kan het kwadraat van nummers uitrekenen met **2 **3 enz enz.

2023-03-31 14:35 UTC, Pincodeert commented on loops.js
> +const asterix = "*";
Ik wist niet dat dit zo ook kan. thanks!

2023-03-31 18:18 UTC, Pincodeert commented on loops.js
> +for(let i = 0; i<5; i++){
dank. aangepast

2023-03-31 18:19 UTC, Pincodeert commented on loops.js
> +for (let i = 1; i < 101; i++) {
dat leest inderdaad wat makkelijker

2023-03-31 18:29 UTC, Pincodeert commented on loops-and-arrays.js
> +    squares[i] = "Het volume van " + squares[i] + " is " + squares[i]*squares[i]*squares[i];
Dank je wel, ook n handige tip!

2023-03-31 18:36 UTC, merged